"""empty message

Revision ID: 364779cf22d3
Revises: 49e80e4b9dcd
Create Date: 2024-03-07 01:18:59.680351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '364779cf22d3'
down_revision = '49e80e4b9dcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_to_exhibit',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('exhibit_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exhibit_id'], ['exhibits.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'exhibit_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_to_exhibit')
    # ### end Alembic commands ###
